spring.application.name=oplib
server.port=8505

# api key: busan weekly popular books, encoding key
busan.best.base-url=https://apis.data.go.kr/6260000/BookLoanBestService
busan.best.service-key=${DATA_BUSAN_BEST_KEY:}

# JDK HttpClient
spring.http.client.factory=jdk

spring.http.client.connect-timeout=5s
spring.http.client.read-timeout=5s

# api key: korea lib info info info, encoding key
lib.info.base-url=https://apis.data.go.kr/B551982/plr/info
lib.info.service-key=${DATA_LIB_INFO_KEY:}

lib.status.base-url=https://apis.data.go.kr/B551982/plr/prst_info
lib.status.service-key=${DATA_LIB_STATUS_KEY:}

lib.seat.base-url=https://apis.data.go.kr/B551982/plr/rlt_rdrm_info
lib.seat.service-key=${DATA_LIB_SEAT_KEY:}


#mariadb set
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/goottlib
spring.datasource.username=root
spring.datasource.password=111111

#mybatis mapper set
mybatis.mapper-locations=classpath:mapper/**/**.xml
mybatis.configuration.cache-enabled=false
mybatis.configuration.jdbc-type-for-null=NULL
