spring.application.name=oplib
server.port=8505

# api key: busan weekly popular books, encoding key
busan.best.base-url=https://apis.data.go.kr/6260000/BookLoanBestService/getBookLoanBest
busan.best.service-key=${DATA_BUSAN_BEST_KEY:}

# JDK HttpClient
spring.http.client.factory=jdk

spring.http.client.connect-timeout=5s
spring.http.client.read-timeout=5s

